/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsTextareaWithImageUploaderRouteImport } from './routes/components/textarea-with-image-uploader'
import { Route as ComponentsImageUploaderRouteImport } from './routes/components/image-uploader'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextareaWithImageUploaderRoute =
  ComponentsTextareaWithImageUploaderRouteImport.update({
    id: '/components/textarea-with-image-uploader',
    path: '/components/textarea-with-image-uploader',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsImageUploaderRoute = ComponentsImageUploaderRouteImport.update({
  id: '/components/image-uploader',
  path: '/components/image-uploader',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/image-uploader': typeof ComponentsImageUploaderRoute
  '/components/textarea-with-image-uploader': typeof ComponentsTextareaWithImageUploaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/image-uploader': typeof ComponentsImageUploaderRoute
  '/components/textarea-with-image-uploader': typeof ComponentsTextareaWithImageUploaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/image-uploader': typeof ComponentsImageUploaderRoute
  '/components/textarea-with-image-uploader': typeof ComponentsTextareaWithImageUploaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/button'
    | '/components/image-uploader'
    | '/components/textarea-with-image-uploader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/button'
    | '/components/image-uploader'
    | '/components/textarea-with-image-uploader'
  id:
    | '__root__'
    | '/'
    | '/components/button'
    | '/components/image-uploader'
    | '/components/textarea-with-image-uploader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsImageUploaderRoute: typeof ComponentsImageUploaderRoute
  ComponentsTextareaWithImageUploaderRoute: typeof ComponentsTextareaWithImageUploaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/textarea-with-image-uploader': {
      id: '/components/textarea-with-image-uploader'
      path: '/components/textarea-with-image-uploader'
      fullPath: '/components/textarea-with-image-uploader'
      preLoaderRoute: typeof ComponentsTextareaWithImageUploaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/image-uploader': {
      id: '/components/image-uploader'
      path: '/components/image-uploader'
      fullPath: '/components/image-uploader'
      preLoaderRoute: typeof ComponentsImageUploaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsImageUploaderRoute: ComponentsImageUploaderRoute,
  ComponentsTextareaWithImageUploaderRoute:
    ComponentsTextareaWithImageUploaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
